name: simple_value_object_annotation
description: An annotation package for value object source code generation.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.0.0"

dependencies:

dev_dependencies:
  lints: ^6.0.0
